language: node_js
sudo: false
node_js:
  - 12
cache:
  directories:
    - node_modules
    - ~/.cache
install:
  - npm install
script:
  - npm run build
  - npm run serve &
  - npm test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
