os: linux
dist: xenial
language: node_js
node_js: 12
install:
  - npm install
script:
  - npm run build
  - npm run serve &
  - npm test

jobs:
  include:
    - stage: release
      deploy:
        skip_cleanup: true # stupid travis complains about this option, yet it requires it
        provider: script
        script:
          - npm run semantic-release
